GET http://localhost:8000


###
GET http://localhost:8000/7856

###
GET http://localhost:8000/notifcation/7856


###
POST http://localhost:8000/notifcation
Content-Type: application/json

{
    "studentId": 7856,
    "toke": "dhajsfs1"
}

###

POST http://localhost:1337
Content-Type: application/json

{
    "id": 6196367,
    "telegram_id": 2787
}

###
{
    "studentId": 7856,
    "joinRequestId": 1,
    "notificationType": "joinRequest"
}
