GET http://localhost:8000


###
GET http://localhost:8000/7856

###
GET http://localhost:8000/notifcation/7856


###
POST http://localhost:8000/notifcation
Content-Type: application/json

{
    "studentId": 7856,
    "toke": "dhajsfs1"
}

###
POST http://localhost:8000/group
Content-Type: application/json

{
    "studentId": 6342,
    "groupId": 2
}


###

POST http://localhost:1337
Content-Type: application/json

{
    "id": 6196367,
    "telegram_id": 2787
}

###
{
    "studentId": 7856,
    "joinRequestId": 1,
    "notificationType": "joinRequest"
}

###
# change telegram id in profile data
POST http://localhost:5000/profile/edit-telegram-id/4669615/9955

###


# get profile data
GET http://localhost:5000/profile/4669615

###
