"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
var express_1 = require("express");
exports.router = (0, express_1.Router)();
exports.default = exports.router;
var studentController_1 = require("../controllers/studentController");
var basicSearchController_1 = require("../controllers/basicSearchController");
exports.router.get('/', studentController_1.getAllStudents);
exports.router.get('/:id', studentController_1.getStudent);
exports.router.get('/basic_search/:text/:student_id', basicSearchController_1.basicSearchResult);
